---
json_rpc_url: https://api.mainnet-beta.solana.com
websocket_url: ''
keypair_path: /Users/oleg.komisarenko/.config/solana/id.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: confirmed
